/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import * as Msdyn365 from '@msdyn365-commerce/core';
import * as React from 'react';
import { comparer, reaction } from 'mobx';
import { observer } from 'mobx-react';
import getCurrentWeatherConditions, { IWeatherConditions, OpenWeatherApiInput } from '../../actions/get-current-weather-conditions.action';
import { ISampleCurrentConditionsData } from './sample-current-conditions.data';
import { ISampleCurrentConditionsProps } from './sample-current-conditions.props.autogenerated';

interface IState {
    units: string;
    updated: Date;
    client: boolean;
}

export interface ISampleCurrentConditionsViewProps extends ISampleCurrentConditionsProps<ISampleCurrentConditionsData> {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    state: any;
    formatter: Msdyn365.ICultureInfoFormatter;
    onClick(): Promise<void>;
    _renderForecast(data: IWeatherConditions, index: number): JSX.Element;
}

/**
 *
 * SampleWeatherCurrentConditions component
 * @extends {React.PureComponent<ISampleCurrentConditionsProps<ISampleCurrentConditionsData>>}
 */
@observer
class SampleCurrentConditions extends React.Component<ISampleCurrentConditionsProps<ISampleCurrentConditionsData>, IState> {
    private readonly formatter: Msdyn365.ICultureInfoFormatter;
    constructor(props: ISampleCurrentConditionsProps<ISampleCurrentConditionsData>) {
        super(props);
        this.state = {
            client: false,
            units: 'F',
            updated: new Date()
        };
        this.toggleUnit.bind(this);
        this._renderForecast.bind(this);
        this.formatter = (this.props.context && this.props.context.cultureFormatter) || new Msdyn365.CultureInfoFormatter('en-us', 'USD');
    }

    public async componentDidMount(): Promise<void> {
        reaction(
            () => this.props.data.favorite_locations.result && this.props.data.favorite_locations.result.map(f => f.id),
            () => {
                console.log('Detected a change');
                return this._refreshData();
            },
            {
                equals: comparer.structural
            }
        );
        this.setState({ client: true });
    }

    public render(): JSX.Element | null {
        const data = this.props.data;

        if (data.forecast.status === 'LOADING' || !this.state.client) {
            return this._renderLoading();
        }

        if (!data || data.forecast.error || data.favorite_locations.error) {
            return this._renderError();
        }

        const viewProps: ISampleCurrentConditionsViewProps = {
            ...this.props,
            onClick: this.toggleUnit.bind(this),
            _renderForecast: this._renderForecast.bind(this),
            formatter: this.formatter,
            state: this.state
        };
        return this.props.renderView(viewProps);
    }

    private async _refreshData(): Promise<void> {
        const { config, context, data } = this.props;
        if (config && config.apiKey && context && data.favorite_locations.result) {
            const apiKey = config.apiKey || '';

            const inputs = data.favorite_locations.result.map(
                f => new OpenWeatherApiInput(apiKey, f, context.request.locale, this.state.units)
            );

            // Calling current weather conditions data action here, Notice, the input passed is an array[],
            void getCurrentWeatherConditions(inputs, context.actionContext).then(foo => {
                this.props.data.forecast.result = foo;
            });

            this.setState({});
        } else {
            console.log('Reaction triggered, but no result available');
        }
    }

    private _renderError(): JSX.Element {
        return (
            <div className='card'>
                <div className='card-header'>Error!</div>
            </div>
        );
    }

    private _renderLoading(): JSX.Element {
        return (
            <div className='spinner-border text-primary' role='status'>
                <span className='sr-only'>Loading...</span>
            </div>
        );
    }

    private _renderForecast(data: IWeatherConditions, index: number): JSX.Element {
        if (!data || !data.weather || !data.weather.length) {
            return (
                <div className='col-lg-3 col-md-6 col-sm-8' key={`cc-${index}`}>
                    No data available
                </div>
            );
        }

        const icon = data.weather[0].icon;
        const caption = data.weather[0].main;
        const date = new Date(data.dt * 1000);
        return (
            <div className='col-lg-3 col-md-6 col-sm-8' key={`cc-${index}`}>
                <div className='card mb-3 mx-5 mx-sm-0'>
                    <div className='card-header'>{data.name}</div>
                    <div className='text-center'>
                        <img
                            src={`//openweathermap.org/themes/openweathermap/assets/vendor/owm/img/widgets/${icon}.png?w=75&m=6`}
                            alt={caption}
                            width='50'
                        />
                        <h4 className='card-title'>{caption}</h4>
                        <h5 className='card-text'>{`${data.main.temp} ${this.state.units}`}</h5>
                        <div className='font-size-small'>
                            <p>
                                {this.formatter.formatDate(date, { weekday: 'short', month: 'short', day: '2-digit' })}
                                &nbsp;
                                {this.formatter.formatTime(date, { hour: 'numeric', minute: 'numeric', second: 'numeric' })}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        );
    }

    private toggleUnit = async () => {
        this.setState({ units: this.state.units === 'F' ? 'C' : 'F' }, async () => {
            await this._refreshData();
        });
    };
}

export default SampleCurrentConditions;
