/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import * as React from 'react';

import { QueryResultSettingsProxy } from '@msdyn365-commerce-modules/retail-actions';
import { ProductSearchResult } from '@msdyn365-commerce/retail-proxy';
import { IShowCategoryProductsProps } from './show-category-products.props.autogenerated';
import { getCategoryProducts, GetCategoryProductsInput } from '../../actions/get-category-products.action';
export interface IShowCategoryProductsViewProps extends IShowCategoryProductsProps<{}> {
    products: ProductSearchResult[] | undefined;
}

/**
 *
 * ShowCategoryProducts component
 * @extends {React.PureComponent<IShowCategoryProductsProps>}
 */

export interface IShowCategoryState {
    categoryProducts: ProductSearchResult[] | undefined;
}

class ShowCategoryProducts extends React.PureComponent<IShowCategoryProductsProps<{}>, IShowCategoryState> {
    public categoryProducts: ProductSearchResult[] | undefined;
    constructor(props: IShowCategoryProductsProps<{}>) {
        super(props);
        this.state = { categoryProducts: [] };
    }

    public async componentDidMount(): Promise<void> {
        const { categoryId, itemsPerPage } = this.props.config;
        const input: GetCategoryProductsInput = new GetCategoryProductsInput(
            categoryId,
            itemsPerPage,
            QueryResultSettingsProxy.getPagingFromInputDataOrDefaultValue(this.props.context.actionContext),
            this.props.context.request.apiSettings
        );
        const categoryProducts = await getCategoryProducts(input, this.props.context.actionContext);
        this.setState({ categoryProducts: categoryProducts });
    }

    public render(): JSX.Element | null {
        const products = this.state.categoryProducts;
        const ShowCategoryViewProps = {
            ...this.props,
            products: products
        };

        return this.props.renderView(ShowCategoryViewProps);
    }
}

export default ShowCategoryProducts;
