/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import { buildMockModuleProps } from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

import * as React from 'react';
import * as renderer from 'react-test-renderer';

import ReadAppSettings from '../read-app-settings';
import { IReadAppSettingsData } from '../read-app-settings.data';
import { IReadAppSettingsConfig, IReadAppSettingsProps } from '../read-app-settings.props.autogenerated';

const mockData: IReadAppSettingsData = {
    actionResponse: {
        text: 'Sample Response Data'
    }
};

const mockConfig: IReadAppSettingsConfig = {
    showText: 'read-app-settings'
};

const mockActions = {};

describe('ReadAppSettings', () => {
    let moduleProps: IReadAppSettingsProps<IReadAppSettingsData>;
    beforeAll(() => {
        moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IReadAppSettingsProps<IReadAppSettingsData>;
    });
    it('renders correctly', () => {
        const component: renderer.ReactTestRenderer = renderer.create(<ReadAppSettings {...moduleProps} />);
        const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
        expect(tree).toMatchSnapshot();
    });
});
