/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import { buildMockModuleProps } from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

import * as React from 'react';
import * as renderer from 'react-test-renderer';

import MyScriptInjector from '../my-script-injector';
import { IMyScriptInjectorData } from '../my-script-injector.data';
import { IMyScriptInjectorConfig, IMyScriptInjectorProps } from '../my-script-injector.props.autogenerated';

const mockData: IMyScriptInjectorData = {
    actionResponse: {
        text: 'Sample Response Data'
    }
};

const mockConfig: IMyScriptInjectorConfig = {
    async: true,
    crossorigin: undefined,
    defer: true,
    inlineScript: "console.log('Test script')"
};

const mockActions = {};

describe('MyScriptInjector', () => {
    let moduleProps: IMyScriptInjectorProps<IMyScriptInjectorData>;
    beforeAll(() => {
        moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IMyScriptInjectorProps<IMyScriptInjectorData>;
    });
    it('renders correctly', () => {
        const component: renderer.ReactTestRenderer = renderer.create(<MyScriptInjector {...moduleProps} />);
        const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
        expect(tree).toMatchSnapshot();
    });
});
