CREATE
or ALTER VIEW [dbo].[view_DimCustomer] AS
SELECT *
FROM OPENROWSET (
		BULK N'https://placeholder_storageaccount.dfs.core.windows.net/placeholder_container/placeholder_datarootpath/Ontologies/Commerce/DimCustomer/*.parquet',
		FORMAT = 'parquet'
	) WITH (
		[CustomerId] 			bigint,
		[Company] 			nvarchar(4),
		[CustomerAccount] 		nvarchar(20),
		[CreditLimit] 			numeric(32, 6),
		[CreditRating] 			nvarchar(100),
		[CustomerClassificationGroup]   nvarchar(100),
		[CustomerGroup] 		nvarchar(100),
		[ModeOfDelivery] 		nvarchar(100),
		[DeliveryTerms] 		nvarchar(100),
		[LineOfBusiness] 		nvarchar(100),
		[MethodOfPayment] 		nvarchar(100),
		[PriceGroup] 			nvarchar(100),
		[SalesDistrict] 		nvarchar(100),
		[SalesGroup] 			nvarchar(100),
		[SalesOrderPool] 		nvarchar(100),
		[Segment] 			nvarchar(100),
		[StatisticsGroup] 		nvarchar(100),
		[Subsegment] 			nvarchar(100),
		[ModifiedDateAndTime] 		datetime2,
		[ModifiedBy] 			nvarchar(100),
		[CreatedDateAndTime] 		datetime2,
		[RecordVersion] 		bigint,
		[Partition] 			bigint,
		[PartyId] 			bigint,
		[PartyNumber] 			nvarchar(100),
		[PartyName] 			nvarchar(100),
		[DateOfBirth] 			date,
		[Gender] 			nvarchar(100),
		[RetailCustomerId] 		bigint,
		[IsRetailCustomer] 		int,
		[AddressId] 			bigint,
		[City] 				nvarchar(100),
		[State] 			nvarchar(100),
		[ZipOrPostalCode] 		nvarchar(100),
		[CountryOrRegion] 		nvarchar(100),
		[CustomerClassificationGroupText] nvarchar(100),
		[CustomerGroupName] 		nvarchar(100),
		[ModeOfDeliveryText] 		nvarchar(100),
		[DeliveryTermsText] 		nvarchar(100),
		[LineOfBusinessDescription] 	nvarchar(100),
		[MethodOfPaymentName] 		nvarchar(100),
		[PriceGroupName] 		nvarchar(100),
		[SalesDistrictDescription] 	nvarchar(100),
		[SalesGroupName] 		nvarchar(100),
		[SalesOrderPoolName] 		nvarchar(100),
		[SegmentDescription] 		nvarchar(100),
		[StatisticsGroupName] 		nvarchar(100),
		[SubsegmentDescription] 	nvarchar(100),
		[TermsOfPayment] 		nvarchar(100),
		[TermsOfPaymentDescription] 	nvarchar(100),
		[CustomerType] 			nvarchar(100),
		[IsMandatoryCreditLimit] 	bigint,
		[IsLoyaltyEnrollmentBlocked] 	bigint,
		[IsPersonalizationDisabled] 	bigint,
		[IsWebActivityTracked] 		bigint,
		[SysProcessingDateTime] 	datetime2,
		[SysIsDeleted] 			int
	) AS [DimCustomer]