CREATE
or ALTER VIEW [dbo].[view_FactSalesOrders] AS
SELECT *
FROM OPENROWSET (
		BULK N'https://placeholder_storageaccount.dfs.core.windows.net/placeholder_container/placeholder_datarootpath/Ontologies/Commerce/FactSalesOrders/*.parquet',
		FORMAT = 'parquet'
	) WITH (
		[SalesLineId] 				bigint,
		[Company] 				nvarchar(4),
		[CustomerAccount] 			nvarchar(20),
		[SalesOrder] 				nvarchar(20),
		[LineNumber] 				numeric(32, 6),
		[NetAmount] 				numeric(32, 6),
		[LotNumber] 				nvarchar(20),
		[SalesUnit] 				nvarchar(10),
		[SalesQuantity] 			numeric(32, 6),
		[DeliverRemainder] 			numeric(32, 6),
		[InvoiceRemainder] 			numeric(32, 6),
		[Currency] 				nvarchar(3),
		[DeliveryType] 				nvarchar(50),
		[LineStatus] 				nvarchar(50),
		[InventoryQuantity] 			numeric(32, 6),
		[ReturnStatus] 				nvarchar(50),
		[RequestedShipDate] 			date,
		[ConfirmedShipDate] 			date,
		[ShipDate] 				date,
		[IsStocked] 				bigint,
		[DimensionNumber] 			nvarchar(20),
		[ItemNumber] 				nvarchar(20),
		[InventoryInvoiceRemainder] 		numeric(32, 6),
		[InventoryDeliverRemainder] 		numeric(32, 6),
		[DiscountAmount] 			numeric(32, 6),
		[MultilineDiscountAmount] 		numeric(32, 6),
		[SalesType] 				nvarchar(50),
		[ModifiedDateAndTime] 			datetime2,
		[ModifiedBy] 				nvarchar(20),
		[CreatedDateAndTime] 			datetime2,
		[CreatedBy] 				nvarchar(20),
		[DefaultDimensionId] 			bigint,
		[SalesTableId] 				bigint,
		[InvoiceAccount] 			nvarchar(20),
		[InventoryUnit] 			nvarchar(10),
		[IsRetailSale] 				int,
		[RetailLoyaltyCardId] 			bigint,
		[ChannelId] 				bigint,
		[StoreNumber] 				nvarchar(10),
		[RetailTerminalId] 			bigint,
		[StatementNumber] 			nvarchar(20),
		[ChannelReference] 			nvarchar(50),
		[RetailTenderTypeId] 			bigint,
		[RetailTenderTypeCardId] 		bigint,
		[CashDiscountAmount] 			numeric(32, 6),
		[DateId] 				int,
		[CustomerId] 				bigint,
		[ItemId] 				bigint,
		[CurrencyId] 				bigint,
		[ReturnNetAmount] 			numeric(32, 6),
		[ReturnQuantity] 			numeric(32, 6),
		[IsReturn] 				int,
		[CompanyId] 				bigint,
		[InventoryDimensionId] 			bigint,
		[ProductVariantId] 			bigint,
		[SysProcessingDateTime] 		datetime2,
		[SysIsDeleted] 				int
	) AS [FactSalesOrders]