CREATE
or ALTER VIEW [dbo].[view_DimProduct] AS
SELECT *
FROM OPENROWSET (
		BULK N'https://placeholder_storageaccount.dfs.core.windows.net/placeholder_container/placeholder_datarootpath/Ontologies/Commerce/DimProduct/*.parquet',
		FORMAT = 'parquet'
	) WITH (
		[ItemId] 				bigint,
		[Company] 				nvarchar(4),
		[ItemNumber] 				nvarchar(20),
		[ABCCodeMargin] 			nvarchar(50),
		[ABCCodeRevenue] 			nvarchar(50),
		[ABCCodeCarryingCost] 			nvarchar(50),
		[ABCCodeValue] 				nvarchar(50),
		[Vendor] 				nvarchar(20),
		[NetWeight] 				numeric(32, 6),
		[TareWeight] 				numeric(32, 6),
		[ProductId] 				bigint,
		[ShelfAdvicePeriodInDays] 		bigint,
		[ShelfLifePeriodInDays] 		bigint,
		[BestBeforePeriodInDays] 		bigint,
		[ModifiedDateAndTime] 			datetime2,
		[ModifiedBy] 				nvarchar(20),
		[CreatedDateAndTime] 			datetime2,
		[CreatedBy] 				nvarchar(20),
		[RecordVersion] 			bigint,
		[Partition] 				bigint,
		[ProductNumber] 			nvarchar(70),
		[ProductSubtype] 			nvarchar(20),
		[CoverageGroup] 			nvarchar(10),
		[CostGroup] 				nvarchar(10),
		[DefaultDimension] 			bigint,
		[ProductName] 				nvarchar(100),
		[ItemGroup] 				nvarchar(20),
		[Season] 				nvarchar(10),
		[ItemModelGroup] 			nvarchar(10),
		[InventoryPrice] 			numeric(32, 6),
		[InventoryPriceQuantity] 		numeric(32, 6),
		[InventoryUnit] 			nvarchar(10),
		[PurchasePrice] 			numeric(32, 6),
		[PurchasePriceQuantity] 		numeric(32, 6),
		[PurchaseUnit] 				nvarchar(10),
		[SalesPrice] 				numeric(32, 6),
		[SalesPriceQuantity] 			numeric(32, 6),
		[SalesUnit] 				nvarchar(10),
		[CoverageGroupName] 			nvarchar(60),
		[CostGroupName] 			nvarchar(60),
		[ItemGroupName] 			nvarchar(60),
		[SeasonDescription] 			nvarchar(60),
		[ItemModelGroupName] 			nvarchar(60),
		[Language] 				nvarchar(7),
		[SysProcessingDateTime] 		datetime2,
		[SysIsDeleted] 				int
	) AS [DimProduct]