/*--------------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * See License.txt in the project root for license information.
 *--------------------------------------------------------------*/

/* eslint-disable no-duplicate-imports */
import CheckoutBillingAddress from './custom-checkout-billing-address';
import CheckoutBillingAddressView from './custom-checkout-billing-address.view';

export * from './custom-checkout-billing-address';
export * from './custom-checkout-billing-address.data';
export {
    ICustomCheckoutBillingAddressConfig,
    ICustomCheckoutBillingAddressProps,
    ICustomCheckoutBillingAddressResources
} from './custom-checkout-billing-address.props.autogenerated';
export * from './custom-checkout-billing-address.view';

export { CheckoutBillingAddress, CheckoutBillingAddressView };
