/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import * as React from 'react';

import { IReadAppSettingsData } from './read-app-settings.data';
import { IReadAppSettingsProps } from './read-app-settings.props.autogenerated';

export interface IReadAppSettingsViewProps extends IReadAppSettingsProps<IReadAppSettingsData> {}

/**
 *
 * ReadAppSettings component
 * @extends {React.PureComponent<IReadAppSettingsProps<IReadAppSettingsData>>}
 */
class ReadAppSettings extends React.PureComponent<IReadAppSettingsProps<IReadAppSettingsData>> {
    public render(): JSX.Element | null {
        return this.props.renderView(this.props);
    }
}

export default ReadAppSettings;
