/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */
import * as React from 'react';
import * as renderer from 'react-test-renderer';
import { buildMockModuleProps } from '@msdyn365-commerce/core-internal';
import { AsyncResult } from '@msdyn365-commerce/retail-proxy';
/// <reference types="jest" />
import { IPowerBi } from '../../../themes/fabrikam-extended/data-actions/DataServiceEntities.g';

import Powerbi from '../powerbi';
import { IPowerbiData } from '../powerbi.data';
import { IPowerbiConfig, IPowerbiProps } from '../powerbi.props.autogenerated';

const mockData: IPowerbiData = {
    // @ts-expect-error partial mock
    powerBIDetails: new Promise(resolve => {
        resolve({
            status: 'SUCCESS',
            result: {}
        } as AsyncResult<IPowerBi>);
    })
};

const mockConfig: IPowerbiConfig = {};

const mockActions = {};

describe('Powerbi', () => {
    let moduleProps: IPowerbiProps<IPowerbiData>;
    beforeAll(() => {
        moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IPowerbiProps<IPowerbiData>;
    });
    it('renders correctly', () => {
        const component: renderer.ReactTestRenderer = renderer.create(<Powerbi {...moduleProps} />);
        const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
        expect(tree).toMatchSnapshot();
    });
});
