/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

/* eslint-disable no-duplicate-imports */
import BusinessAccountAddress from './custom-business-account-address';
import BusinessAccountAddressView from './custom-business-account-address.view';

export * from './custom-business-account-address';
export * from './custom-business-account-address.data';
export {
    ICustomBusinessAccountAddressConfig,
    ICustomBusinessAccountAddressProps,
    ICustomBusinessAccountAddressResources
} from './custom-business-account-address.props.autogenerated';
export * from './custom-business-account-address.view';

export { BusinessAccountAddress, BusinessAccountAddressView };
