/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

/**
 * Mocked resources shared for test cases.
 */
export const mockResources = {
    findInStoreLinkText: 'Find in store',
    findInStoreHeaderText: 'Buy now, pick up in a store',
    findInStoreDescriptionText: 'Search for product availability at stores within {radius} miles of you.',
    priceFree: 'Free',
    originalPriceText: 'Was:',
    currentPriceText: 'Now:',
    addToCartText: 'Add to cart',
    outOfStockText: 'Out of Stock',
    averageRatingAriaLabel: 'Average {0} of {1} stars',
    selectDimensionFormatString: 'Choose a {0}',
    productDimensionTypeColor: 'Color',
    productDimensionTypeConfiguration: 'Configuration',
    productDimensionTypeSize: 'Size',
    productDimensionTypeStyle: 'Style',
    productDimensionTypeAmount: 'Amount',
    addToOrderTemplateButtonText: 'Add to order template',
    addToOrderTemplateMessage: 'Added to your order template',
    addItemToOrderTemplateError: 'Unable to add item to order template',
    addToWishlistButtonText: 'Add to Wishlist',
    createOrderTemplateHeader: 'createOrderTemplateHeader',
    orderTemplateTitle: 'orderTemplateTitle',
    orderTemplateNameAriaLabel: 'orderTemplateNameAriaLabel',
    createOrderTemplateDescription: 'createOrderTemplateDescription',
    defaultOrderTemplateName: 'defaultOrderTemplateName',
    createOrderTemplateButtonText: 'createOrderTemplateButtonText',
    createNewOrderTemplateButtonText: 'createNewOrderTemplateButtonText',
    cancelNewOrderTemplateCreationButtonText: 'cancelNewOrderTemplateCreationButtonText',
    addToOrderTemplateHeader: 'addToOrderTemplateHeader',
    addToOrderTemplateButtonTooltip: 'This product cannot be added to order template due to custom pricing',
    noOrderTemplatesMessage: 'noOrderTemplatesMessage',
    noOrderTemplatesDescription: 'noOrderTemplatesDescription',
    createAnOrderTemplateButtonText: 'createAnOrderTemplateButtonText',
    cancelOrderTemplateCreationButtonText: 'cancelOrderTemplateCreationButtonText',
    viewOrderTemplateButtonText: 'viewOrderTemplateButtonText',
    continueShoppingButtonText: 'continueShoppingButtonText',
    itemAddedToOrderTemplateHeaderItemOneText: 'itemAddedToOrderTemplateHeaderItemOneText',
    itemAddedToOrderTemplateHeaderItemFormatText: 'itemAddedToOrderTemplateHeaderItemFormatText',
    itemAddedToOrderTemplateHeaderMessageText: 'itemAddedToOrderTemplateHeaderMessageText',
    duplicatedProductsHeader: 'duplicatedProductsHeader',
    duplicatedProductsDescription: 'duplicatedProductsDescription',
    updateQuantityButtonText: 'updateQuantityButtonText',
    cancelDuplicateItemsButtonText: 'cancelDuplicateItemsButtonText',
    selectTemplatesText: 'Select a template or create a new one. You have {0} template(s).',
    addToTemplateButtonText: 'Add to template',
    lineItemsText: '{0} line item(s)',
    removeFromWishlistButtonText: 'Remove from Wishlist',
    addToWishlistMessage: 'Added to your wishlist',
    removedFromWishlistMessage: 'Removed from your wishlist',
    addItemToWishlistError: 'Unable to add item to wishlist',
    removeItemFromWishlistError: 'Unable to remove item from wishlist',
    nameOfWishlist: 'My Wishlist',
    inputQuantityAriaLabel: 'Quantity To Purchase',
    productQuantityHeading: 'Quantity',
    errorMessageOutOfStock: 'This product is out of stock',
    errorMessageOutOfRangeOneLeft: 'There is only one product left. Please choose quantity within the available range',
    errorMessageOutOfRangeFormat: 'There are only {numLeft} products left. Please choose quantity within the available range',
    productDimensionTypeColorErrorMessage: 'Color is required. Please choose a color',
    productDimensionTypeConfigurationErrorMessage: 'Configuration is required. Please choose a configuration',
    productDimensionTypeSizeErrorMessage: 'Size is required. Please choose a size',
    productDimensionTypeStyleErrorMessage: 'Style is required. Please choose a style',
    productDimensionTypeAmountErrorMessage: 'Amount is required. Please choose an amount',
    buyboxErrorMessageHeader: 'There are some issues',
    addedToCartFailureMessage: 'Add to cart failed. Please refresh and retry',
    maxQuantityLimitText:
        'You already have {curQuantity} of this item in your shopping bag. You can only add {maxQuantity} of this item to your shopping bag',
    invalidSmallCustomAmountText: 'The minimum amount is {minAmount}',
    invalidLargeCustomAmountText: 'The maximum amount is {maxAmount}',
    shopSimilarLooksText: 'Shop Similar Looks',
    shopSimilarDescriptionText: 'Shop Similar Description',
    buyBoxGoToCartText: 'View bag and checkout',
    buyBoxContinueShoppingText: 'Continue shopping',
    closeNotificationLabel: 'Close',
    buyBoxSingleItemText: '1 item',
    buyBoxMultiLineItemFormatText: '{0} items',
    buyBoxHeaderMessageText: ' added to bag',
    maxQuantityText: 'The maximum quantity to purchase for this product is {max}.',
    minQuantityText: 'The minimum quantity to purchase for this product is {min}.',
    buyboxKeyInPriceLabelHeading: 'Custom amount',
    descriptionTextToShowAllPickupOptions: 'This product is availble for the following pick up methods',
    addedQuantityText: 'addedQuantityText',
    decrementButtonAriaLabel: 'Decrease the quantity by 1',
    incrementButtonAriaLabel: 'Increase quantity by 1',
    quickViewbuttonText: 'Quick View',
    nextScreenshotFlipperText: 'nextScreenshotFlipperText',
    previousScreenshotFlipperText: 'previousScreenshotFlipperText',
    seeDetailsbuttontext: 'See Details',
    loadingText: 'Loading...',
    findInStoreNotAvailableTextButton: 'This item is out of stock',
    findInStoreNotAvailableDescription: 'This product is currently unavailable for pick up.',
    informationIconText: 'Information'
};
