/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import * as React from 'react';

import { IApiTestData } from './api-test.data';
import { IApiTestProps } from './api-test.props.autogenerated';

export interface IApiTestViewProps extends IApiTestProps<IApiTestData> {
    categories: string;
}

/**
 *
 * ApiTest component
 * @extends {React.PureComponent<IApiTestProps<IApiTestData>>}
 */
class ApiTest extends React.PureComponent<IApiTestProps<IApiTestData>> {
    public render(): JSX.Element | null {
        const {
            data: { categories }
        } = this.props;

        let CategoryList = 'no categories returned';
        if (categories && categories.result) {
            CategoryList = '';

            for (let i = 0; i < categories.result.length; i++) {
                CategoryList += `${categories.result[i].Name}, `;
            }
        }

        const ViewProps = {
            ...this.props,
            categories: CategoryList.toString()
        };

        return this.props.renderView(ViewProps);
    }
}

export default ApiTest;
