IF (SELECT OBJECT_ID('[ext].[CONTOSORETAILPRICINGPROPERTYDEFINITION]')) IS NOT NULL 
BEGIN
   DROP TABLE [EXT].CONTOSORETAILPRICINGPROPERTYDEFINITION
END
GO


CREATE TABLE [ext].[CONTOSORETAILPRICINGPROPERTYDEFINITION](
    [CONTOSOPROPERTYTYE] [INT] NOT NULL,
	[RECID] [BIGINT] NOT NULL,
	[DATAAREAID] [NVARCHAR] (4) NOT NULL,
 CONSTRAINT [PK_EXT_CONTOSORETAILPRICINGPROPERTYDEFINITION] PRIMARY KEY CLUSTERED 
(
	[DATAAREAID] ASC,
	[RECID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

GRANT INSERT, DELETE, UPDATE, SELECT ON OBJECT::[ext].[CONTOSORETAILPRICINGPROPERTYDEFINITION] TO [DataSyncUsersRole];
GO
